# the environment file (this file) defines an environment in which acceptance tests can run
#
# The tests use the symbolic names for the CMS management server and CMSs (publishers). This
# allows each environment to use different publishers and allows a test developer to have their
# own publishers in an environment.

cms_domain: d.movetv.com
cms_username: admin.move  # User name and passwords for login into cms publishers configured under 'publishers' section
cms_password: xlontestit
browser: Chrome
angular_1_browser: Firefox

management_server:
  hostname: d-gp2-cmsmgt-2.d.movetv.com
  username: admin.move
  password: xlontestit

publishers:
  testpublisher:  # this is the symbolic name used in features and steps
    name: acceptance_test
    host_alias: acceptance
    admin_name: admin
    admin_email: noreply@dishdigital.com
  upstream:
    name: acceptanceupstream
    host_alias: accup
    admin_name: admin
    admin_email: noreply@dishdigital.com
  downstream:
    name: acceptancedownstream
    host_alias: accdown
    admin_name: admin
    admin_email: noreply@dishdigital.com
  ingestionpublisher:
    name: ingestion
    host_alias: ingestion
    admin_name: admin
    admin_email: noreply@dishdigital.com
  cms_ui: # different publisher for ui tests
    name: uiapps
    host_alias: uiapps
    admin_name: admin
    admin_email: noreply@dishdigital.com

# Ensure 'clientfacing' NEVER gets under 'publishers' section above else uberdeath tool will kill everything.
# It is only for read only test purposes and points to actual qa/beta/prod depending upon the environment
clientfacing:
    name: bbtv.d.movetv.com
    host_alias: bbtv
    hostname: bbtv.d.movetv.com
    username: admin.move
    password: xlontestit
    designated_folder_name: New Releases
    pub_id: 4c2689ec

env_specific_settings:
    ad_info_network_id: "381962"
    is_prod_env: false
    cms_vod_ready_exchange: dynamux_mq
    ad_service_url: http://adapt.qcg20.movetv.com/http://5d40a.s.fwmrm.net/ad/g/1


servers:
  management:  # DON Server Where Publishers Are Created At!!!
    hostname: d-gp2-cmsmgt-2.d.movetv.com
    username: administrator
    password: xlontestit
    ssh_key_filename:
    port:

  management_read_only:  # DON Server BBTV for running ReadOnly commands/tools!!!
    hostname: d-gp2-cmsmgt-1.d.movetv.com
    username: administrator
    password: xlontestit
    ssh_key_filename:
    port:

  ui_apps:
    hostname: d-gp2-cmsmg-2.imovetv.com
    username: administrator
    password: xlontestit
    ssh_key_filename:
    server_username: administrator
    server_password: xlontestit
    port: 6500
    super_admin: {username: mgadmin@dish.com, password: test!ng, fullname: Super Duper Admin}
    apps:
      channel_management:
        alias: Channels
        admin: {username: mg_test_cm_admin@dish.com, fullname: Test Channel Mgmt Admin}
        read: {username: mg_test_cm_read@dish.com, fullname: Test Channel Mgmt Read}
        update: {username: mg_test_cm_update@dish.com, fullname: Test Channel Mgmt Update}
        twoapps: {username: twoupdates@dish.com, fullname: Tommy TwoApps}
        password: test!ng
      domain_management:
        alias: Domains
        admin: {username: mg_test_dm_admin@dish.com, fullname: Test Domain Mgmt Admin}
        read: {username: mg_test_dm_read@dish.com, fullname: Test Domain Mgmt Read}
        update: {username: mg_test_dm_update@dish.com, fullname: Test Domain Mgmt Update}
        password: test!ng
      offer_management:
        alias: Offer Management
        admin: {username: mg_test_om_admin@dish.com, fullname: Test Offer Mgmt Admin}
        read: {username: mg_test_om_read@dish.com, fullname: Test Offer Mgmt Read}
        update: {username: mg_test_om_update@dish.com, fullname: Test Offer Mgmt Update}
        password: test!ng
      source_management:
        alias: Sources
        admin: {username: mg_test_sm_admin@dish.com, fullname: Test Source Mgmt Admin}
        read: {username: mg_test_sm_read@dish.com, fullname: Test Source Mgmt Read}
        update: {username: mg_test_sm_update@dish.com, fullname: Test Source Mgmt Update}
        password: test!ng
      image_curation:
        alias: Image Curation
        admin: {username: mg_test_ic_admin@dish.com, fullname: Test Img Curation Admin}
        read: {username: mg_test_ic_read@dish.com, fullname: Test Img Curation Read}
        update: {username: mg_test_ic_update@dish.com, fullname: Test Img Curation Update}
        password: test!ng
      subpack_management:
        alias: Subscription Packs
        admin: {username: mg_test_pm_admin@dish.com, fullname: Test Subpack Mgmt Admin}
        read: {username: mg_test_pm_read@dish.com, fullname: Test Subpack Mgmt Read}
        update: {username: mg_test_pm_update@dish.com, fullname: Test Subpack Mgmt Update}
        password: test!ng
      ribbon_management:
        alias: Screen Composer
        admin: {username: mg_test_rb_admin@dish.com, fullname: Test Ribbon Mgmt Admin}
        read: {username: mg_test_rb_read@dish.com, fullname: Test Ribbon Mgmt Read}
        update: {username: mg_test_rb_update@dish.com, fullname: Test Ribbon Mgmt Update}
        twoapps: {username: twoupdates@dish.com, fullname: Tommy TwoApps}
        password: test!ng
      entitlement_management:
        alias: Entitlements
        admin: {username: mg_test_en_admin@dish.com, fullname: Test Entitlements Privilege}
        password: test!ng
      promotion_management:
        alias: Promotion Management
        admin: {username: mg_test_pr_admin@dish.com, fullname: Test Promo Admin}
        read: {username: mg_test_pr_read@dish.com, fullname: Test Promo Read}
        update: {username: mg_test_pr_update@dish.com, fullname: Test Promo Update}
        password: test!ng

  cms_apps:
    username: mgadmin@dish.com
    password: test!ng

  epg_tools:
    hostname: d-gp2-epg-4.imovetv.com
    username: administrator
    password: xlontestit
    ssh_key_filename:
    mappings_dir: /opt/move/mappings
    local_storage_dir: /var/db_files      # Some tests still need this.

  epg_tools_database:
    hostname: "d-gp2-dbpgepgtools-1.imovetv.com"
    port: 5432
    username: epgtools_test_user
    password: "jcijkj!!98zxc"
    db_name: epgtools_test

  ota_app:
    hostname: d-gp2-ota-2.imovetv.com
    username: administrator
    password: xlontestit
    ssh_key_filename:
    port: 8000
    buffer_time_s: 5

  ota_ivory_source_db:  # db connected to ota for making ivory db queries. Used for OTA read only as well
    hostname: d-gp2-cmsunk-1.imovetv.com
    username: ivory
    password: ivory
    ssh_key_filename:
    port: 5432
    db_name: ivory

  salt_master:
    hostname: salt.dev.movetv.com
    username: root
    password:
    ssh_key_filename: ~/.ssh/id_rsa
    port:

  elastic_search_db:
    hostname: d-gp2-es48-1.imovetv.com
    username:
    password:
    ssh_key_filename:
    port: 9200

  image_service:  # Also used by OTA image host comparison
    create_hostname: d-gp2-img-2.imovetv.com
    read_hostname: d-gp2-img-2.imovetv.com
    username: administrator
    password: xlontestit
    ssh_key_filename:
    port: 80
    latency: 0  # Wait time in seconds before getting image from read_hostname, post uploading it on create_hostname

  image_retriever:
    hostname: d-gp2-ir-2.imovetv.com
    username: administrator   # eng no longer working
    password: xlontestit
    ssh_key_filename:
    port:

  geo_location:
    hostname: d-gp2-geo-1.d.movetv.com
    username: administrator
    password: xlontestit
    ssh_key_filename:
    port: 80

  ivory_server:  # For Ivory End to End testing
    hostname: d-gp2-ivory-1.imovetv.com
    username: administrator   # eng no longer working
    password: xlontestit
    ssh_key_filename:
    port: 80

  ivory_database:  # Used by ivory test only (non-bbtv tests)
    hostname: d-gp2-ivory-1.imovetv.com
    port: 5432
    username: ivory
    password: ivory
    db_name: ivory

  ivory_readonly_server:  # For Ivory read only testing
    hostname: d-gp2-cmsunk-1.imovetv.com
    username: administrator
    password: xlontestit
    ssh_key_filename:
    port: 80

  ebony_readonly_server:  # NEW EBONY SERVER FOR IVORY RESOURCES
    hostname: d-gp2-cmsebony.imovetv.com
    username: administrator
    password: xlontestit
    ssh_key_filename:
    port: 80

  roviftp_server:
    hostname: d-gp2-roviftp-1.imovetv.com
    username: administrator
    password: xlontestit
    ssh_key_filename:
    port:

  psql_db:
    hostname: d-gp2-dbp19-1.d.movetv.com
    username: cmsmgt
    password: DevJ2bva63xKX5FxKDGbsGeJM7L6gkcQunpn
    ssh_key_filename:
    port: 5432
    db_name: cmsmgt002

  promotion_db:
    hostname: d-gp2-dbpgmgpromotions-1.imovetv.com
    username: app_promotion_service
    password: Jo9iXLt84R32m=tWg,Mpy/.qagTuu*Ly
    ssh_key_filename:
    port: 5432
    db_name: promotion_service_test

  farallon:
    exchange: farallon_publish_messages
    env: dev

  metacloud:
    kafka_host: aws-prelim-kafka01.metacloud.media:9092
    topic: SlingTV.asset.status.metacloud

  media_view:
    hostname: mvprod.dishonline.com
    client_secret: nvyfncid84jf7rhe6dfbf7jg8
    client_key: e23asery428d23

  rabbit_mq:
    hostname: d-gp2-cmsmq-2.d.movetv.com
    username: devcms
    password: devcms
    ui_port: 15672
    don_pub_id: XXXXXXXX
    esni_exchange: esni
    service_port: 5672
    vhost: Null

  espn_media:
    hostname: watch.auth.api.espn.com
    api_key: zzfjgt4zr9s9u2fj5ctwzv87

  dyna_admin:
    env: dev
    hostname: d-gp2-dynadm-1.imovetv.com

  psql_db_clientfacing:  # Required for pagination test case only (READ ONLY QUERY TO GET COUNT OF OBJECTS BEFORE HITTING API)
    hostname: d-gp2-dbp21-1.d.movetv.com
    username: cmsmgt
    password: DevJ2bva63xKX5FxKDGbsGeJM7L6gkcQunpn
    ssh_key_filename:
    port: 5432
    db_name: cmsmgt001
    pub_id: 4c2689ec

  program_service:
    hostname: d-gp2-cmsprog-2.imovetv.com
    username: administrator
    password: xlontestit
    port: 8995
    kafka:
      franchise_sync_topic: franchise_test
      season_sync_topic: season_test
      program_sync_topic: program_test
      asset_sync_topic: asset_test
      team_sync_topic: team_test
      program_update_topic: program-update_test
      consumer_id: ps_test
      readonly_consumer_id: ps_test_readonly
    database:
      hostname: d-gp2-dbpgmgprogramservice-1.imovetv.com
      port: 5432
      username: app_program_service_test
      password: 'wtpJ]y9nPBpZ2mFMBey%36qUt?+7a%Kh'
      db_name: program_service_test

  program_service_consumer_2:
    hostname: d-gp2-cmsmg-2.imovetv.com
    username: administrator
    password: xlontestit
    port: 8995

  tally_supair_service:
    host:
      hostname: d-gp2-cmstal-2.imovetv.com
      username: administrator
      password: xlontestit
      ssh_key_filename:
    kafka:
      metacloud_supair_write_topic: autosuggest_data_for_sling_test
      metacloud_supair_synonym_write_topic: supair.slingtv.autosuggest_test
      tally_supair_sync_topic: tally-supair_test
      supair_synonym_topic: tally-supair-synonym_test
      program_sync_topic: program_test
      program_service_consumer_group: ps_test
      metacloud_consumer_group: mg_supair_consumer_dev_test
      synonym_consumer_group: mg_supair_synonym_consumer_dev_test
      readony_consumer_group: mg_supair_consumer_dev_test_1
    database:
      hostname: d-gp2-dbpgmgtally-1.imovetv.com
      port: 5432
      user: app_tally_test
      password: kk$K]Yc[PmLGCwq6yvL9KyM$tgP4(7n2
      database: tally_test

  tally_autosuggest_service:
    hostname: d-gp2-cmstal-2.imovetv.com
    username: administrator
    password: xlontestit
    kafka:
      autosuggest_topic: tally-autosuggest_test
    database:
      hostname: d-gp2-dbpgmgtally-1.imovetv.com
      port: 5432
      user: app_tally_test
      password: kk$K]Yc[PmLGCwq6yvL9KyM$tgP4(7n2
      database: tally_test

  cms_networker:
    hostname: d-gp2-cmsmg-2.imovetv.com
    username: administrator
    password: xlontestit
    port: 8000
    kafka:
      avail_consumer_id: cms_networker_avails_test
      asset_consumer_id: cms_networker_asset_test
      asset_sync_topic: asset_test
      avail_sync_topic: availability_test
      program_update_consumer_id: cms_networker_program_update_test
      program_update_topic: program-update_test
      channel_consumer_id: cms_networker_channel_test
      channel_sync_topic: channel_test
      presentation_view_topic: presentation-view_test
      readonly_consumer_id: cms_networker_test_readonly
    database:
      hostname: d-gp2-dbpgmgnetworker-1.imovetv.com
      port: 5432
      username: app_networker_test
      password: W,pAX[AZwYWae2642M?P?jbphJJfd&E3
      db_name: networker_test

  collection_service:
    host:
      hostname: d-gp2-cmsmg-2.imovetv.com
      username: administrator
      password: xlontestit
      ssh_key_filename:
      port: 8898
    elasticsearch:
      hostname: d-gp2-es48-1.imovetv.com
      port: 9200
      collections_index: collections_test
      tiles_index: tiles_test
      username: administrator
      password: xlontestit
    elasticsearch2:
      hostname: d-gp2-es48-2.imovetv.com
      port: 9200
      collections_index: collections_test
      tiles_index: tiles_test
      username: administrator
      password: xlontestit
    elasticsearch3:
      hostname: d-gp2-es48-3.imovetv.com
      port: 9200
      collections_index: collections_test
      tiles_index: tiles_test
      username: administrator
      password: xlontestit
    kafka:
      collections_topic: collections_test
      collections_connector: MG_ES_SkynetSinkConnector-collections_test
      collections_connector_group: connect-MG_ES_SkynetSinkConnector-collections_test
      tiles_topic: tiles_test
      tiles_connector: MG_ES_TilesSinkConnector_Test
      tiles_connector_group: connect-MG_ES_TilesSinkConnector_test
      readonly_consumer_id: cs_test_readonly  # Consumer for testing purpose to read/fast_farward  from pv/tiles topics
      pv_topic: presentation-view_test
      pv_consumer_id: collections-service-presentation-view-test
      autosuggest_topic: tally-autosuggest_test
      autosuggest_consumer_id: collection-service-tally-suggest-test

  promotion_service:
    hostname: d-gp2-cmsmg-2.imovetv.com
    username: administrator
    password: xlontestit
    app_username: mgadmin@dish.com
    app_password: test!ng
    ssh_key_filename:
    port: 8996
    kafka:
      avail_consumer_id: promotion-service-availability_test
      avail_sync_topic: availability_test
      asset_sync_topic: asset_test
      asset_consumer_id: promotion-service-asset_test
      program_update_consumer_id: promotion-service-program-update_test
      program_update_topic: program-update_test
      channel_consumer_id: promotion-service-channel_test
      channel_sync_topic: channel_test
      subpack_consumer_id: promotion-service-subpack_test
      subpack_sync_topic: subscription-pack_test
      presentation_view_topic: presentation-view_test
      readonly_consumer_id: promotion-service_test_readonly

  mgsearch:
    hostname: d-gp2-mgsearch-2.imovetv.com
    username: administrator
    password: xlontestit
    ssh_key_filename:
    port: 80
    kafka:
      presentation_view_topic: presentation-view_test
      pv_consumer_id: mgsearch_pv_consumer_test
      tally_supair_topic: tally-supair_test
      tally_supair_syn_topic: tally-supair-synonym_test
      tally_consumer_id: mgsearch_tally_test
      mgsearch_consumer_id: mgsearch_dev_test
    database:
      hostname: d-gp2-dbpgmgsearch-1.imovetv.com
      username: app_mgsearch_test
      password: 73zbXf}VDEFbq(DWKt$&34rr2pGf)fAi
      port: 5432
      db_name: mgsearch_test

  skynet:
    hostname: d-gp2-cmsmg-2.imovetv.com
    username: administrator
    password: xlontestit
    port: 8899
    api_username: mgadmin@dish.com
    api_password: test!ng
    es_hostname: d-gp2-es48-1.imovetv.com
    es_port: 9200
    collections_topic: collections_test
    connector: MG_ES_SkynetSinkConnector-collections_test  # Not used

  # media graph config here, keep in one place per munish -srp
  mediagraph:
    rabbit:
      host: d-gp2-cmsmq-2.d.movetv.com
      username: devcms
      password: devcms
      port: 5672
      heartbeat: 10
      cms_sync_queue: cms.D90E2616.sync.mg_test   # may not need this, just use main exchange and routing sync routing key
      cms_routing_key: cms.D90E2616.sync.#   # rabbit mq routing key: cms.<pubid>.sync.<everything> (guid, etc.)
      exchange: main
    # is there something needed for storm/topology directly ? (assume this is only used through kafka)
    kafka:
      cluster: d-gp2-cmszk-1.imovetv.com     # or you could put individual brokers in list
      zookeeper: 'd-gp2-cmszk-1.imovetv.com:2181/kafka10'  
      hosts:
        - 'd-gp2-cmskafka-4.imovetv.com:9092'
        - 'd-gp2-cmskafka-5.imovetv.com:9092'
        - 'd-gp2-cmskafka-6.imovetv.com:9092'
      port: 2181
      connector_host: 'd-gp2-cmskafka-4.imovetv.com:8083'
      common_config:
        bootstrap_servers: d-gp2-cmskafka-4.imovetv.com
        api_version_request: true
        session_timeout_ms: 6000
        group_id: acceptance
      producer_config:
        bootstrap.servers: d-gp2-cmskafka-4.imovetv.com
        api.version.request: true
        session.timeout.ms: 6000
        group.id: acceptance
      consumer_config:
        bootstrap.servers: d-gp2-cmskafka-4.imovetv.com
        api.version.request: true
        session.timeout.ms: 6000
        group.id: acceptance
        default.topic.config:
          auto.offset.reset: smallest
      kafka_consumer_config:
        bootstrap_servers: [d-gp2-cmskafka-4.imovetv.com]
        group_id: acceptance
        auto_offset_reset: latest
        consumer_timeout_ms: 1000
      all_topics:             # maintain list of topics set up in kafka or those that are required (end with _test)
        - asset
        - folder
        - availability
        - franchise
        - program
        - season
        - channel
        - collections
        - presentation-view
        - program-update
        - tiles
        - subscription-pack
        - tally-autosuggest
        - tally-supair
        - team
      cms_sync_topics:        # maintain list of topics that get messages pushed from cms / sync messages
        - asset
        - folder
        - availability
        - franchise
        - program
        - season
        - channel
        - subscription-pack
        - team
    storm:
      ui: http://d-gp2-sp-1.d.movetv.com:8080  # we will need this possibly to use rest api
      topology:
        name: rabbitkafka-topology-test
        id: rabbitkafka-topology-test-5-1494444978
      rest:
        cluster: none
        supervisor: none
        topology: none
        last_response: none
